### ISSUE TITLE
Add information in the about page

### ISSUE THREAD

**Issue by achyuthcodes30** [acmpesuecc/Bazaar#13]
Add a descriptive write up to give some details about Bazaar.

**Comment by ZeusPod** [comment]
You can assignment me this ?

**Comment by achyuthcodes30** [comment]
Hey!  Sorry this issue is part of an internal hacktoberfest event.

**Comment by avdhagam** [comment]
I want to be assigned to this

**Comment by SNEH-17PATEL** [comment]
CAN I GET ASSIGNED??????

**Comment by achyuthcodes30** [comment]
Assigned to @avdhagam

**Comment by Rojas-Binny** [comment]
Can I get assigned?

**Comment by Manvith-M-Nayak** [comment]
can i get assigned?

**Comment by arun-bonal** [comment]
please assign me

**Comment by Arty1912** [comment]
achyuth pls be so kind as to accept my request to work on your wonderful and soul touching piece of art
thank you

**Comment by diishanbhag** [comment]
please assign this to meeee

**Comment by Arshdeep-Bhatia** [comment]
can I get assigned

**Comment by amankhandelwaal** [comment]
Can I get assigned?

**Comment by marshallmathers0** [comment]
can i get assigned?

**Comment by PsychCodez** [comment]
can i get assigned

**Comment by achyuthcodes30** [comment]
@avdhagam updates?

**Comment by AmeyaKhanzode** [comment]
please for god's sake can i get assigned?

**Comment by achyuthcodes30** [comment]
Waiting on updates please remain patient

**Comment by pj1840** [comment]
can i get assigned to this

**Comment by achyuthcodes30** [comment]
Issue has been solved! Anyone wanting to work on this please add fresh comments.

**Comment by Prajwal-creator007** [comment]
can I get assigned?

**Comment by devanshishukla17** [comment]
hi can i pls get assigned on this issue :)

**Comment by amrit-george** [comment]
can i be assigned this issue?

**Comment by Rishav1git** [comment]
can u assign this to me
