### ISSUE TITLE
Add a new product

### ISSUE THREAD

**Issue by achyuthcodes30** [acmpesuecc/Bazaar#15]
Create a new superuser and add a product using the django admin interface.

**Comment by Hiyanachnani** [comment]
hiii please assign this issue to me

**Comment by sid-nc** [comment]
can u assign this to me

**Comment by umarahmed10** [comment]
can i get assigned

**Comment by SourabhHegde14** [comment]
can i be assigned

**Comment by akshatb29** [comment]
can i get assigned

**Comment by siaa1308** [comment]
can i get assigned

**Comment by siaa1308** [comment]
can i get assigned

**Comment by siaa1308** [comment]
can i get assigned

**Comment by Arshdeep-Bhatia** [comment]
can i get assigned

**Comment by 7Akshu77** [comment]
Can I get assigned to this issue

**Comment by achyuthcodes30** [comment]
assigned to @akshatb29

**Comment by devanshishukla17** [comment]
can i get assigned ???????

**Comment by pj1840** [comment]
can i get assigned to this

**Comment by likhitharigela** [comment]
Can i get assigned to it pls

**Comment by amrit-george** [comment]
can i get assigned this issue?

**Comment by Rohan123R** [comment]
@achyuthcodes30  Can i please get assigned to #15

**Comment by achyuthcodes30** [comment]
@Rohan123R you have been assigned.

**Comment by avaneeshmahendra29** [comment]
can i get assigned

**Comment by devanshishukla17** [comment]
hi can I get assigned this issue:)

**Comment by amankhandelwaal** [comment]
hey, can i get assigned to this issue #15

**Comment by achyuthcodes30** [comment]
@amankhandelwaal you have been assigned this issue.

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by 7Akshu77** [comment]
can I get assigned to this issue

**Comment by prerana1809** [comment]
hey can i be assigned to issue #15

**Comment by amrit-george** [comment]
can i get assigned to this issue? #15

**Comment by achyuthcodes30** [comment]
Unassigning @amankhandelwaal

**Comment by achyuthcodes30** [comment]
Assigning this issue to @ssether04

**Comment by achyuthcodes30** [comment]
@ssether04 updates ??

**Comment by 411sst** [comment]
@achyuthcodes30 

linked a pr
