### ISSUE TITLE
Fix cards on the home page 

### ISSUE THREAD

**Issue by achyuthcodes30** [acmpesuecc/Bazaar#16]
The cards on the homepage currently require a constant image resolution to be uploaded. Fix the image sizing issue to ensure consistency across all cards regardless of the resolution of the image uploaded by vendors. 

# Reproduce the bug
Add a product through the django admin interface(make sure you're a superuser) with an arbitrary image resolution and view the home page. You can see the card formed is not consistent with the others.

# Check if the issue is resolved
To check if your code handles the issue you can add a product with an arbitrary image resolution and view the home page. Do note that the home page displays only the six latest products as a result of a limit statement in the backend code.

**Comment by devanshishukla17** [comment]
can i pls get assigned the issue

**Comment by BhavikaPradeep** [comment]
can i please try fixing this issue.
i am gonna be working on this ,hope u understand.

**Comment by dishashrivas1ava** [comment]
can you please assign this issue to me

**Comment by Shreevardhancoder** [comment]
can u please assign the  issue of fixing bug in fixing cards on home page  to me ?

**Comment by achyuthcodes30** [comment]
Assigned to @BhavikaPradeep

**Comment by dhanyaprabhu05** [comment]
Can I get this assigned

**Comment by dhruvsharma1910** [comment]
can u please assign the issue

**Comment by DedLad** [comment]
assign it to me

**Comment by achyuthcodes30** [comment]
@Shreevardhancoder you have been assigned this issue.

**Comment by devanshishukla17** [comment]
hi can i pls get assigned this issue:)

**Comment by achyuthcodes30** [comment]
@Shreevardhancoder updates??

**Comment by Shreevardhancoder** [comment]
sir i am working on it sir 
i will finish as soon as possible

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by shweta-v-18** [comment]
can u please assign me #16

**Comment by Rohan123R** [comment]
@achyuthcodes30  can please 
get it assigned if it is not solved

**Comment by achyuthcodes30** [comment]
@Shreevardhancoder How's it going??
