### ISSUE TITLE
Vendors - Part 1 - Create signup and login functionality for vendors

### ISSUE THREAD

**Issue by achyuthcodes30** [acmpesuecc/Bazaar#19]
Your task is to create a new table for vendors ( Just one possible solution) and write to it through a sign up page for these vendors. Also implement login functionality that authenticates vendors. Both the vendor signup and login option must be present in the corner dropdown menu for any user that is not logged in. In part 2 of this issue the add and delete options for categories and products will only be available to these vendors.

**Comment by samarth777** [comment]
can you assign this to me

**Comment by parvashah305** [comment]
can you assign this to me

**Comment by achyuthcodes30** [comment]
Assigned to @samarth777

**Comment by Keeru-2005** [comment]
can you please assign this to me?

**Comment by ankitam389** [comment]
can you assign this to me?

**Comment by PsychCodez** [comment]
can you assign this to me

**Comment by parvashah305** [comment]
It's been 40 minutes the first person has assigned pls assigned to me

**Comment by achyuthcodes30** [comment]
@samarth777 what is the update?

**Comment by achyuthcodes30** [comment]
@samarth777 ??

**Comment by achyuthcodes30** [comment]
@samarth777 you have been unassigned from this issue due to lack of communication. Any other takers do leave a comment.

**Comment by parvashah305** [comment]
i want it

**Comment by parvashah305** [comment]
where do i write it

**Comment by DedLad** [comment]
give it to me

**Comment by shreyahegde26** [comment]
can i please get assigned to this??

**Comment by achyuthcodes30** [comment]
@DedLad you have been assigned this issue.

**Comment by achyuthcodes30** [comment]
@DedLad updates??

**Comment by achyuthcodes30** [comment]
@DedLad please update.

**Comment by shreyahegde26** [comment]
can i get assigned to this please??

**Comment by Keeru-2005** [comment]
can i work on this pls?

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by DedLad** [comment]
@achyuthcodes30 wya man

**Comment by shreyahegde26** [comment]
can i get assigned to this please?

**Comment by 411sst** [comment]
can i get assigned if this is still open?

**Comment by devanshishukla17** [comment]
can i get this issue signed?#19

**Comment by devanshishukla17** [comment]
can i get this issue assigned?#19
